version: 2
models:
  - name: cryptopunks_CryptoPunksMarket_evt_Assign
    columns:
      - name: to
      - name: punkIndex
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_evt_Transfer
    columns:
      - name: from
      - name: to
      - name: value
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_evt_PunkTransfer
    columns:
      - name: from
      - name: to
      - name: punkIndex
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_evt_PunkOffered
    columns:
      - name: punkIndex
      - name: minValue
      - name: toAddress
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_evt_PunkBidEntered
    columns:
      - name: punkIndex
      - name: value
      - name: fromAddress
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_evt_PunkBidWithdrawn
    columns:
      - name: punkIndex
      - name: value
      - name: fromAddress
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_evt_PunkBought
    columns:
      - name: punkIndex
      - name: value
      - name: fromAddress
      - name: toAddress
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_evt_PunkNoLongerForSale
    columns:
      - name: punkIndex
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_call_name
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_call_punksOfferedForSale
    columns:
      - name: _0
      - name: output_isForSale
      - name: output_punkIndex
      - name: output_seller
      - name: output_minValue
      - name: output_onlySellTo
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_call_enterBidForPunk
    columns:
      - name: punkIndex
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_call_totalSupply
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_call_acceptBidForPunk
    columns:
      - name: punkIndex
      - name: minPrice
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_call_decimals
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_call_setInitialOwners
    columns:
      - name: addresses
      - name: indices
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_call_withdraw
    columns:
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_call_imageHash
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_call_nextPunkIndexToAssign
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_call_punkIndexToAddress
    columns:
      - name: _0
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_call_standard
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_call_punkBids
    columns:
      - name: _0
      - name: output_hasBid
      - name: output_punkIndex
      - name: output_bidder
      - name: output_value
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_call_balanceOf
    columns:
      - name: _0
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_call_allInitialOwnersAssigned
    columns:
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_call_allPunksAssigned
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_call_buyPunk
    columns:
      - name: punkIndex
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_call_transferPunk
    columns:
      - name: to
      - name: punkIndex
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_call_symbol
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_call_withdrawBidForPunk
    columns:
      - name: punkIndex
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_call_setInitialOwner
    columns:
      - name: to
      - name: punkIndex
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_call_offerPunkForSaleToAddress
    columns:
      - name: punkIndex
      - name: minSalePriceInWei
      - name: toAddress
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_call_punksRemainingToAssign
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_call_offerPunkForSale
    columns:
      - name: punkIndex
      - name: minSalePriceInWei
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_call_getPunk
    columns:
      - name: punkIndex
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_call_pendingWithdrawals
    columns:
      - name: _0
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: cryptopunks_CryptoPunksMarket_call_punkNoLongerForSale
    columns:
      - name: punkIndex
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
