# Default airflow tag to deploy
defaultAirflowTag: "2.2.2"

# Airflow version (Used to make some decisions based on Airflow Version being deployed)
airflowVersion: "2.2.2"

images:
  airflow:
    repository: {{IMAGE_REPOSITORY}}
    tag: {{IMAGE_TAG}}

env:
  - name: AWS_ACCESS_KEY_ID
    value: {{AWS_ACCESS_KEY_ID}}
  - name: AWS_SECRET_ACCESS_KEY
    value: {{AWS_SECRET_ACCESS_KEY}}
  - name: AWS_DEFAULT_REGION
    value: {{AWS_DEFAULT_REGION}}

# Airflow database & redis config
data:
  metadataSecretName: airflow-database
  resultBackendSecretName: airflow-result-database

# Flask secret key for Airflow Webserver: `[webserver] secret_key` in airflow.cfg
webserverSecretKeySecretName: airflow-webserver-secret

# Fernet key settings
# Note: fernetKey can only be set during install, not upgrade
fernetKey: {{FERNET_KEY}}

# PgBouncer settings
pgbouncer:
  # Enable PgBouncer
  enabled: true

# Configuration for postgresql subchart
# Not recommended for production
postgresql:
  enabled: false

# Git sync
dags:
  gitSync:
    enabled: true

    # git repo clone url
    # ssh examples ssh://git@github.com/apache/airflow.git
    # git@github.com:apache/airflow.git
    # https example: https://github.com/apache/airflow.git
    repo: https://github.com/datawaves-xyz/blockchain-dbt-airflow.git
    branch: master
    # subpath within the repo where dags are located
    # should be "" if dags are at repo root
    subPath: "/dags"

    env:
    - name: GIT_SYNC_PERMISSIONS
      value: '0777'

config:
  core:
    parallelism: 120
  webserver:
    expose_config: true
  celery:
    worker_concurrency: 8

workers:
  replicas: 1

  resources:
    requests:
      memory: 3Gi
    limits:
      memory: 3Gi

  keda:
    enabled: true
    namespaceLabels: {}
    # How often KEDA polls the airflow DB to report new scale requests to the HPA
    pollingInterval: 5
    # How many seconds KEDA will wait before scaling to zero.
    # Note that HPA has a separate cooldown period for scale-downs
    cooldownPeriod: 30
    # Minimum number of workers created by keda
    minReplicaCount: 0
    # Maximum number of workers created by keda
    maxReplicaCount: 15

  extraInitContainers:
   - name: volume-logs
     image: busybox

logs:
  persistence:
    # Enable persistent volume for storing logs
    enabled: true
    storageClassName: aws-efs
