name: Generate dbt code

on:
  push:
    branches:
      - "main"
    paths:
      - "contracts/**"

jobs:
  codegen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Set up python env
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "adopt"

      - name: Cache python pip
        uses: actions/cache@v2
        id: cache-pip
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache local Maven repository
        uses: actions/cache@v2
        id: cache-mvn
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/java/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - run: pip install --upgrade blockchain-dbt eth-hash[pycryptodome]

      - run: bdbt ethereum_codegen

      - name: Run read-yaml action
        id: yaml-data
        uses: KJ002/read-yaml@main
        with:
          file: "./dbt_project.yml"
          key-path: '["version"]'

      - name: Upload jar to s3
        uses: zdurham/s3-upload-github-action@master
        env:
          FILE: blockchain-dbt-udf-${{ steps.yaml-data.outputs.data }}.jar
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          S3_KEY: ${{ secrets.AWS_S3_FOLDER }}blockchain-dbt-udf-${{ steps.yaml-data.outputs.data }}.jar
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Commit files
        run: |
          git config --local user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --local user.name "${{ secrets.GIT_USER }}"
          git add .
          git commit -m "Codegen" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
          branch: main
