ethereum_source:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      schema: "{{ env_var('SPARK_DATABASE', 'not-set') }}"
      host: "{{ env_var('SPARK_HOST', 'not-set') }}"
      port: "{{ env_var('SPARK_PORT', '-1') | as_number }}"
      threads: 16
