version: 2

models:
  - name: stg_ethereum__transactions

  - name: stg_ethereum__blocks

  - name: stg_ethereum__logs

  - name: stg_ethereum__traces

  - name: stg_ethereum__token_transfers

  - name: stg_ethereum__contracts

  - name: stg_ethereum__tokens

  - name: stg_ethereum__receipts
