version: 2

macros:
  - name: hex
    description: Converts `expression` to hexadecimal.
    docs:
      show: true

  - name: substring
    description: Returns a substring of the supplied string or binary value.
    docs:
      show: true
    arguments:
      - name: expression
        type: string or binary
      - name: position
        type: integer
      - name: length
        type: integer

  - name: binary_literal
    description: A binary literal is used to specify a byte sequence value.
    docs:
      show: true
    arguments:
      - name: expression
        type: string
        description: Any hexadecimal symbols from 0 to F.

  - name: displayed_amount
    description: Adjust the token amount according to the decimals.
    docs:
      show: true
    arguments:
      - name: original_amount
        type: integer
      - name: decimals
        type: integer

  - name: binary_to_numeric
    description: Convert a binary column to numeric type.
    docs:
      show: true
    arguments:
      - name: expression
        type: binary

  - name: binary_to_address
    description: Convert a binary column to a hex string started with 0x
    docs:
      show: true
    arguments:
      - name: expression
        type: binary