version: 2
models:
  - name: yearn_YearnGovernance_evt_OwnershipTransferred
    columns:
      - name: previousOwner
      - name: newOwner
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_evt_RewardAdded
    columns:
      - name: reward
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_evt_RewardPaid
    columns:
      - name: user
      - name: reward
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_evt_Staked
    columns:
      - name: user
      - name: amount
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_evt_Withdrawn
    columns:
      - name: user
      - name: amount
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_DURATION
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_balanceOf
    columns:
      - name: account
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_bpt
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_breaker
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_claimFees
    columns:
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_config
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_earned
    columns:
      - name: account
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_exit
    columns:
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_feesPaidIn
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_getReward
    columns:
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_governance
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_initialize
    columns:
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_isOwner
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_lastTimeRewardApplicable
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_lastUpdateTime
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_lock
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_minimum
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_notifyRewardAmount
    columns:
      - name: reward
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_owner
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_period
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_periodFinish
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_proposalCount
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_proposals
    columns:
      - name: _0
      - name: output_id
      - name: output_proposer
      - name: output_totalForVotes
      - name: output_totalAgainstVotes
      - name: output_start
      - name: output_end
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_propose
    columns:
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_renounceOwnership
    columns:
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_rewardPerToken
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_rewardPerTokenStored
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_rewardRate
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_rewards
    columns:
      - name: _0
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_seize
    columns:
      - name: _token
      - name: amount
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_setBreaker
    columns:
      - name: _breaker
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_setGovernance
    columns:
      - name: _governance
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_setLock
    columns:
      - name: _lock
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_setMinimum
    columns:
      - name: _minimum
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_setPeriod
    columns:
      - name: _period
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_setReward
    columns:
      - name: _feesPaidIn
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_setRewardDistribution
    columns:
      - name: _rewardDistribution
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_stake
    columns:
      - name: amount
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_totalSupply
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_transferOwnership
    columns:
      - name: newOwner
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_updateFees
    columns:
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_userRewardPerTokenPaid
    columns:
      - name: _0
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_voteAgainst
    columns:
      - name: id
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_voteFor
    columns:
      - name: id
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_voteLock
    columns:
      - name: _0
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_withdraw
    columns:
      - name: amount
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_yBal
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_yIndex
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_ySupplyIndex
    columns:
      - name: _0
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: yearn_YearnGovernance_call_yfi
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
