version: 2
models:
  - name: superrare_SuperRare_evt_WhitelistCreator
    columns:
      - name: _creator
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_evt_Bid
    columns:
      - name: _bidder
      - name: _amount
      - name: _tokenId
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_evt_AcceptBid
    columns:
      - name: _bidder
      - name: _seller
      - name: _amount
      - name: _tokenId
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_evt_CancelBid
    columns:
      - name: _bidder
      - name: _amount
      - name: _tokenId
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_evt_Sold
    columns:
      - name: _buyer
      - name: _seller
      - name: _amount
      - name: _tokenId
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_evt_SalePriceSet
    columns:
      - name: _tokenId
      - name: _price
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_evt_OwnershipTransferred
    columns:
      - name: previousOwner
      - name: newOwner
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_evt_Transfer
    columns:
      - name: _from
      - name: _to
      - name: _tokenId
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_evt_Approval
    columns:
      - name: _owner
      - name: _approved
      - name: _tokenId
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_call_addNewTokenWithEditions
    columns:
      - name: _uri
      - name: _editions
      - name: _salePrice
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_call_setSalePrice
    columns:
      - name: _tokenId
      - name: _salePrice
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_call_name
    columns:
      - name: output__name
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_call_approve
    columns:
      - name: _to
      - name: _tokenId
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_call_totalSupply
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_call_currentBidDetailsOfToken
    columns:
      - name: _tokenId
      - name: output_0
      - name: output_1
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_call_approvedFor
    columns:
      - name: _tokenId
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_call_acceptBid
    columns:
      - name: _tokenId
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_call_isWhitelisted
    columns:
      - name: _creator
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_call_bid
    columns:
      - name: _tokenId
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_call_tokensOf
    columns:
      - name: _owner
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_call_setMaintainerPercentage
    columns:
      - name: _percentage
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_call_whitelistCreator
    columns:
      - name: _creator
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_call_ownerOf
    columns:
      - name: _tokenId
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_call_originalTokenOfUri
    columns:
      - name: _uri
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_call_balanceOf
    columns:
      - name: _owner
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_call_owner
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_call_symbol
    columns:
      - name: output__symbol
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_call_cancelBid
    columns:
      - name: _tokenId
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_call_salePriceOfToken
    columns:
      - name: _tokenId
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_call_transfer
    columns:
      - name: _to
      - name: _tokenId
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_call_takeOwnership
    columns:
      - name: _tokenId
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_call_setCreatorPercentage
    columns:
      - name: _percentage
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_call_tokenURI
    columns:
      - name: _tokenId
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_call_creatorOfToken
    columns:
      - name: _tokenId
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_call_buy
    columns:
      - name: _tokenId
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_call_addNewToken
    columns:
      - name: _uri
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_call_creatorPercentage
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_call_maintainerPercentage
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: superrare_SuperRare_call_transferOwnership
    columns:
      - name: newOwner
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
