version: 2
models:
  - name: rariable_ExchangeStateV1_evt_OperatorAdded
    columns:
      - name: account
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeStateV1_evt_OperatorRemoved
    columns:
      - name: account
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeStateV1_evt_OwnershipTransferred
    columns:
      - name: previousOwner
      - name: newOwner
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeStateV1_call_addOperator
    columns:
      - name: account
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeStateV1_call_completed
    columns:
      - name: _0
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeStateV1_call_getCompleted
    columns:
      - name: key
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeStateV1_call_getCompletedKey
    columns:
      - name: key
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeStateV1_call_isOperator
    columns:
      - name: account
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeStateV1_call_isOwner
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeStateV1_call_owner
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeStateV1_call_removeOperator
    columns:
      - name: account
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeStateV1_call_renounceOwnership
    columns:
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeStateV1_call_setCompleted
    columns:
      - name: key
      - name: newCompleted
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeStateV1_call_transferOwnership
    columns:
      - name: newOwner
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeV1_evt_Buy
    columns:
      - name: sellToken
      - name: sellTokenId
      - name: sellValue
      - name: owner
      - name: buyToken
      - name: buyTokenId
      - name: buyValue
      - name: buyer
      - name: amount
      - name: salt
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeV1_evt_Cancel
    columns:
      - name: sellToken
      - name: sellTokenId
      - name: owner
      - name: buyToken
      - name: buyTokenId
      - name: salt
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeV1_evt_OwnershipTransferred
    columns:
      - name: previousOwner
      - name: newOwner
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeV1_call_beneficiary
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeV1_call_buyerFeeSigner
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeV1_call_cancel
    columns:
      - name: key
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeV1_call_erc20TransferProxy
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeV1_call_exchange
    columns:
      - name: order
      - name: sig
      - name: buyerFee
      - name: buyerFeeSig
      - name: amount
      - name: buyer
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeV1_call_isOwner
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeV1_call_ordersHolder
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeV1_call_owner
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeV1_call_prepareBuyerFeeMessage
    columns:
      - name: order
      - name: fee
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeV1_call_prepareMessage
    columns:
      - name: order
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeV1_call_renounceOwnership
    columns:
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeV1_call_setBeneficiary
    columns:
      - name: newBeneficiary
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeV1_call_setBuyerFeeSigner
    columns:
      - name: newBuyerFeeSigner
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeV1_call_state
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeV1_call_transferOwnership
    columns:
      - name: newOwner
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeV1_call_transferProxy
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeV1_call_transferProxyForDeprecated
    columns:
      - name: output_0
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeV2_evt_AdminChanged
    columns:
      - name: previousAdmin
      - name: newAdmin
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeV2_evt_BeaconUpgraded
    columns:
      - name: beacon
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeV2_evt_Upgraded
    columns:
      - name: implementation
      - name: evt_block_number
      - name: evt_block_time
      - name: evt_index
      - name: evt_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeV2_call_admin
    columns:
      - name: output_admin_
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeV2_call_changeAdmin
    columns:
      - name: newAdmin
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeV2_call_implementation
    columns:
      - name: output_implementation_
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeV2_call_upgradeTo
    columns:
      - name: newImplementation
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
  - name: rariable_ExchangeV2_call_upgradeToAndCall
    columns:
      - name: newImplementation
      - name: data
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
