config-version: 2
name: ethereum_source
profile: ethereum_source
version: 0.1.0
require-dbt-version:
  - ">=1.0.0"
  - <2.0.0
models:
  ethereum_source:
    stg:
      +materialized: view
      +schema: stg_ethereum
      +tags:
        - chain_ethereum
        - level_standardize
        - proj_global
    codegen:
      curve:
        +schema: curve
        +tags:
          - chain_ethereum
          - level_parse
          - proj_curve
      superrare:
        +schema: superrare
        +tags:
          - chain_ethereum
          - level_parse
          - proj_superrare
      cryptopunks:
        +schema: cryptopunks
        +tags:
          - chain_ethereum
          - level_parse
          - proj_cryptopunks
      yearn:
        +schema: yearn
        +tags:
          - chain_ethereum
          - level_parse
          - proj_yearn
      looksrare:
        +schema: looksrare
        +tags:
          - chain_ethereum
          - level_parse
          - proj_looksrare
      opensea:
        +schema: opensea
        +tags:
          - chain_ethereum
          - level_parse
          - proj_opensea
      foundation:
        +schema: foundation
        +tags:
          - chain_ethereum
          - level_parse
          - proj_foundation
      rariable:
        +schema: rariable
        +tags:
          - chain_ethereum
          - level_parse
          - proj_rariable
vars:
  ethereum_source:
    transactions: "{{ source('ethereum', 'transactions') }}"
    token_transfers: "{{ source('ethereum', 'token_transfers') }}"
    tokens: "{{ source('ethereum', 'tokens') }}"
    contracts: "{{ source('ethereum', 'contracts') }}"
    blocks: "{{ source('ethereum', 'blocks') }}"
    logs: "{{ source('ethereum', 'logs') }}"
    traces: "{{ source('ethereum', 'traces') }}"
    receipts: "{{ source('ethereum', 'receipts') }}"
    using_traces: true
    using_logs: true
    using_token_transfers: true
    using_receipts: false
    dt: "not-set"
