version: 2

models:
  - name: wyvern_data
    config:
      materialized: view
  - name: opensea_trades
    config:
      materialized: ephemeral
  - name: nft_trades
  - name: nft_trades_partition_by_dt
  - name: nft_tokens
    config:
      materialized: view
  - name: nft_token_metadata
    config:
      materialized: view
